export default class Auth {
    static SIGNIN_PROGRESS = 'SIGNIN_PROGRESS';
    static SIGNIN_SUCCESSFUL = 'SIGNIN_SUCCESSFUL';
    static SIGNIN_REJECTED = 'SIGNIN_REJECTED';
    static SIGNIN_PROGRESS_VERIFY = 'SIGNIN_PROGRESS_VERIFY';
    static SIGNIN_SUCCESSFUL_VERIFY = 'SIGNIN_SUCCESSFUL_VERIFY';
    static SIGNIN_REJECTED_VERIFY = 'SIGNIN_REJECTED_VERIFY';

    // Create Profile//
    static CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS';
    static CREATE_PRIFILE_ERROR = 'CREATE_PROFILE_ERROR';
    static CREATE_PROFILE_PROGRESS = 'CREATE_PROFILE_PROGRESS';


    // Profile Fetch //
    static GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
    static GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';
    static GET_PROFILE_PROGRESS = 'GET_PROFILE_PROGRESS';




    /////////////// PUBLIC PROFILE //////////////////////
    static GET_ALL_USER_PUBLIC_SUCCESS = 'GET_ALL_USER_PUBLIC';
    static GET_ALL_USER_PUBLIC_ERROR = 'GET_ALL_USER_PUBLIC_ERROR';
    static GET_ALL_USER_PUBLIC_PROGRESS = 'GET_ALL_USER_PUBLIC_PROGRESS';

    static Get_USER_REQ = "Get_USER_REQ";

    static SIGNUP_PROGRESS = "SIGNUP_PROGRESS";
    static SIGNUP_ERROR = "SIGNUP_ERROR";

    static GET_Experience_SUCCESS = "GET_Experience_SUCCESS";
    static GET_Skill_SUCCESS = "GET_Skill_SUCCESS";

    static GET_Skill_NEW_ARRAY = "GET_Skill_NEW_ARRAY";


    static GET_TEXT_PROGRESS = "GET_TEXT_PROGRESS";

    static GET_TEXT_SUCCESS = "GET_TEXT_SUCCESS";


    static GET_ALL_MESSAGES = "GET_ALL_MESSAGES";

    static GET_MESSAGE_LIST = "GET_MESSAGE_LIST";

    // static GET_HIDE_CITY = "GET_HIDE_CITY";

    // static GET_HIDE_PHONE = "GET_HIDE_PHONE";

    // static GET_PROFESSION_PHONE = "GET_PROFESSION_PHONE";
    // 


}


